### ISSUE TITLE
New balancer and resolver APIs

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#1388]
This is the issue to track progress on the new balancer and resolver APIs.
Please see gRFC L9 for details: https://github.com/grpc/proposal/pull/30 ([discussion link](https://groups.google.com/forum/#!topic/grpc-io/rUDN7-cZvz8))

- [x] Add new interfaces and wrapper for the old balancer #1408
- [x] New implementation for balancers, including pickfirst, roundrobin and grpclb
  - [x] pickfirst #1506
  - [x] roundrobin #1506
  - [x] grpclb #1558
- [x] Support switching balancers
  - [x] based on service config #1670
  - [x] based on address type (use grpclb if resolved addresses contain grpclb) #1692

The issue with `failfast`(as mentioned in #1432) will also be fixed.

**Comment by trusch** [comment]
Just for reference,I tested this for my usecase (see #1694) and I noticed two things:

* The query interval of the DNS resolver is not configurable (30min)
* Dead connections are also retried 30mins before getting removed
