### ISSUE TITLE
addrConn/ClientConn cleanup

### ISSUE THREAD

**Issue by menghanl** [grpc/grpc-go#1742]
List of issues to be fixed:
 - [ ] Fix the behavior of addrConn with empty address list #1683
 - [x] return the underlying network error from ClientConn #1633
 - [ ] Finer-grained locks or atomics for addrConn #1669
 - [x] Invoke hangs in client after server presents an incorrect certificate #1656 

 - [ ] Not send address's Metadata as metadata for RPCs on the connection ([set here](https://github.com/grpc/grpc-go/blob/2720857d978b9873027f6d739d74794428f49c03/clientconn.go#L1117), and [used here](https://github.com/grpc/grpc-go/blob/2720857d978b9873027f6d739d74794428f49c03/transport/http2_client.go#L473)).
Should do this explicitly through options (`NewSubConn` option?) instead.

- [ ] Keep retrying with exponential backoff even if the error is non-temporary.

**Comment by jadekler** [comment]
> Keep retrying with exponential backoff even if the error is non-temporary.

What's the rationale here? In the case of missing certs, this could be painful.

**Comment by menghanl** [comment]
@jadekler The reason is, other client behaviors depend on the fact that retrying always happens, for example, resolver re-resolving (https://github.com/grpc/grpc-go/issues/1795#issuecomment-365098419)
