### ISSUE TITLE
Channelz service implementation progress tracking

### ISSUE THREAD

**Issue by lyuxuan** [grpc/grpc-go#1920]
Channelz language-agnostic design: https://github.com/grpc/proposal/blob/master/A14-channelz.md

### Progress on golang implementation:
- [x] channelz database internals, APIs, interfaces. Entity registration/deletion instrumentation. (#1811)
- [x] Entity metric collection. (#1909)
- [x] rpc service implementation (#1919)
- [x] more info to be filled in (##1965)
   -  [ ] refName (TODO)
   -  [x] security
   - [x] socket options, etc.
